source 'https://rubygems.org'

gem 'beaker',                        '~> 5.1'
gem 'ffi',                           '~> 1.15'
gem 'hiera-eyaml',                   '~> 3.3'
gem 'json',                          '~> 2.6'
gem 'nokogiri',                      '~> 1.14'
gem 'onceover-codequality',          git: 'https://github.com/tuxmea/onceover-codequality.git', branch: 'lint_strings_4'
gem 'onceover-lookup',               '~> 0.1', '>= 0.1.1'
gem 'onceover-octocatalog-diff',     '~> 0.1', '>= 0.1.8'
gem 'onceover',                      '~> 3.20'
gem 'parallel',                      '~> 1.22', '>= 1.22.1'
gem 'puppet-lint',                   '~> 4.0'
gem 'puppet-strings',                '~> 4.0'
gem 'puppet-syntax',                 '~> 3.3'
gem 'puppet',                        '~> 8.0'
gem 'puppetlabs_spec_helper',        '~> 6.0'
gem 'r10k',                          '~> 3.15'
gem 'ra10ke',                        '~> 2.0'
gem 'rspec-puppet',                  '~> 3.0'
gem 'rspec-puppet-facts',            '~> 2.0', '>= 2.0.5'
gem 'rspec-puppet-utils',            '~> 3.4'
gem 'rubocop-performance',           '~> 1.17'
gem 'rubocop-rspec',                 '~> 2.20'
gem 'rubocop-rake',                  '~> 0.6'
gem 'rubocop',                       '~> 1.50'
gem 'unf_ext',                       '~> 0.0.8'
gem 'yamllint',                      '~> 0.0.9'
gem 'voxpupuli-acceptance',          '~> 1.2'
gem 'voxpupuli-puppet-lint-plugins', '~> 5.0'
gem 'minitest',                      '~> 5.18'
