name: publish 🐳 Docker image

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tags
        shell: python
        run: |
          import re
          from packaging.version import parse

          version = "${{ github.ref }}".replace("refs/tags/v", "")
          version = "${{ github.ref }}".split("/")[2]
          image   = "ghcr.io/${{ github.repository }}"
          tags    = set()

          if version.startswith('v'):
            tags.add(f"{image}:{version}")
            if not parse(version).is_prerelease:
              tags.add(f"{image}:latest")
          else:
            tags.add(f"{image}:{version}")

          tags = ",".join(sorted(list(tags)))
          print(f"::set-output name=tags::{tags}")
        id: tags

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
