name: publish 🐳 Docker image

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tags
        shell: python
        run: |
          import re
          from packaging.version import parse

          image = "ghcr.io/${{ github.repository }}"
          tags  = set()

          if "${{ github.ref }}".startswith('refs/pull'):
            version = "${{ github.event.pull_request.head.ref }}"

          if "${{ github.ref }}".startswith('refs/heads'):
            version = "${{ github.event.push.head.ref }}"

          if version.startswith('v'):
            tags.add(f"{image}:latest")

          if version == 'main':
            version = "development"

          tags.add(f"{image}:{version}")
          tags = ",".join(sorted(list(tags)))
          print(f"::set-output name=tags::{tags}")
        id: tags

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
